import os
import json
import shutil
import logging
import re
from typing import List, Dict, Optional, Tuple
from pathlib import Path
from datetime import datetime
import time

# -------------------------------------------------------------------------
# DEPENDENCY SERVICE INTEGRATION
# -------------------------------------------------------------------------
try:
    from dependency_builder.dependency_service import DependencyService
    from dependency_builder.config import DependencyBuilderConfig
    DEPENDENCY_SERVICE_AVAILABLE = True
except ImportError:
    DEPENDENCY_SERVICE_AVAILABLE = False
    DependencyService = None
    DependencyBuilderConfig = None

# -------------------------------------------------------------------------
# LLM TOOLS INTEGRATION
# -------------------------------------------------------------------------
try:
    from utils.common.llm_tools import LLMTools, LLMConfig
except ImportError:
    raise ImportError("LLMTools not found. Ensure utils.common.llm_tools is available.")

# -------------------------------------------------------------------------
# EMAIL REPORTER INTEGRATION
# -------------------------------------------------------------------------
try:
    from utils.common.email_reporter import EmailReporter, EmailConfig
except ImportError:
    EmailReporter = None
    EmailConfig = None

# -------------------------------------------------------------------------
# EXCEL WRITER INTEGRATION
# -------------------------------------------------------------------------
try:
    from utils.common.excel_writer import ExcelWriter, ExcelStyle
except ImportError:
    raise ImportError("ExcelWriter not found. Ensure utils.common.excel_writer is available.")

# -------------------------------------------------------------------------
# GLOBAL CONFIG INTEGRATION
# -------------------------------------------------------------------------
try:
    from utils.parsers.global_config_parser import GlobalConfig
except ImportError:
    GlobalConfig = None


class CodebaseFixerAgent:
    """
    Holistic Fixer Agent with Semantic Context Awareness.

    UPDATES:
    1. Uses DependencyService to inject struct/function definitions into the prompt.
    2. Maintains strict chunking and safety guards.
    3. Reads from the shared CCLS cache generated by the Analysis Agent.
    4. Uses modern dependency injection pattern for configuration.
    5. Replaces CodebaseEmailReporter with EmailReporter.
    6. Uses ExcelWriter instead of xlsxwriter/pandas.
    7. Fixes bare except clauses with specific exception handling.
    """

    TARGET_CHUNK_CHARS = 8000
    HARD_CHUNK_LIMIT = 20000
    CONTEXT_OVERLAP_LINES = 25

    def __init__(
        self,
        codebase_root: str,
        directives_file: str,
        backup_dir: str,
        output_dir: str = "./out",
        config: Optional['GlobalConfig'] = None,
        llm_tools: Optional[LLMTools] = None,
        dep_config: Optional['DependencyBuilderConfig'] = None,
        dry_run: bool = False,
        verbose: bool = False
    ):
        self.codebase_root = Path(codebase_root).resolve()
        self.directives_path = Path(directives_file).resolve()
        self.backup_dir = Path(backup_dir).resolve()
        self.output_dir = str(Path(output_dir).resolve())
        self.project_name = self.codebase_root.name
        self.start_time = datetime.now()

        # Configuration
        self.config = config
        self.dry_run = dry_run
        self.verbose = verbose

        # Setup Logging
        logging.basicConfig(
            filename='fixer_agent_debug.log',
            level=logging.INFO,
            format='%(asctime)s - %(levelname)s - %(message)s'
        )
        self.logger = logging.getLogger(__name__)

        # Initialize LLM Tools
        self._initialize_llm_tools(llm_tools)

        # Initialize Dependency Service
        self._initialize_dependency_service(dep_config)

    def _initialize_llm_tools(self, llm_tools: Optional[LLMTools] = None):
        """Initialize LLM tools with dependency injection pattern."""
        if llm_tools:
            self.llm_tools = llm_tools
            if self.verbose:
                self.logger.info("[Agent] LLM Tools injected externally.")
        elif self.config:
            model_str = self.config.get("llm.model")
            self.llm_tools = LLMTools(model=model_str) if model_str else LLMTools()
            if self.verbose:
                self.logger.info(f"[Agent] LLM Initialized from config with model: {model_str}")
        else:
            self.llm_tools = LLMTools()
            if self.verbose:
                self.logger.info("[Agent] LLM Initialized with defaults from environment.")

    def _initialize_dependency_service(self, dep_config: Optional['DependencyBuilderConfig'] = None):
        """Initialize dependency service with proper configuration."""
        if not DEPENDENCY_SERVICE_AVAILABLE:
            self.logger.warning("[!] DependencyService not available. Fixes will lack semantic context.")
            self.dep_service = None
            return

        try:
            if dep_config:
                self.dep_service = DependencyService(config=dep_config)
            else:
                dep_config = DependencyBuilderConfig.from_env() if hasattr(DependencyBuilderConfig, 'from_env') else DependencyBuilderConfig()
                self.dep_service = DependencyService(config=dep_config)
            if self.verbose:
                self.logger.info("[Agent] DependencyService initialized.")
        except Exception as e:
            self.logger.warning(f"[!] Failed to initialize DependencyService: {e}")
            self.dep_service = None

    def run_agent(
        self,
        report_filename: str = "final_execution_audit.xlsx",
        email_recipients: Optional[List[str]] = None
    ) -> Dict:
        """
        Execute the fixer agent on the codebase.

        Args:
            report_filename: Output Excel report filename
            email_recipients: Email addresses for report delivery. If None, uses config.

        Returns:
            Dictionary with execution results
        """
        self.logger.info(f"[*] Starting Holistic Fixer Agent on {self.codebase_root}")
        if self.dep_service:
            self.logger.info(f"[*] Dependency Service Enabled. Using cache at: {self.output_dir}/{self.project_name}")

        if self.dry_run:
            self.logger.info("[NOTICE] DRY RUN MODE ENABLED: No files will be modified.")

        # Resolve email recipients
        if email_recipients is None and self.config:
            email_recipients = self.config.get("email.recipients", [])
        if not email_recipients:
            email_recipients = []

        directives = self._load_directives()
        if not directives:
            self.logger.warning("[!] No directives found.")
            return {"status": "no_directives", "results": []}

        grouped_tasks = self._group_by_file(directives)
        results = []
        file_count = 0
        total_files = len(grouped_tasks)

        for file_path_str, tasks in grouped_tasks.items():
            file_count += 1
            # Path resolution
            if os.path.isabs(file_path_str):
                try:
                    file_path = Path(file_path_str).resolve()
                except ValueError:
                    file_path = Path(file_path_str)
            else:
                file_path = (self.codebase_root / file_path_str).resolve()

            # Use Absolute Path for dependency lookup
            abs_path_str = str(file_path)

            self.logger.info(f"[{file_count}/{total_files}] Processing File: {file_path.name} ({len(tasks)} items)...")

            if not file_path.exists():
                self.logger.warning(f"    [!] File not found: {file_path}")
                for t in tasks:
                    results.append({**t, "final_status": "FILE_NOT_FOUND"})
                continue

            active_tasks = [t for t in tasks if t.get('action') != 'SKIP']
            skipped_tasks = [t for t in tasks if t.get('action') == 'SKIP']

            for t in skipped_tasks:
                results.append({**t, "final_status": "SKIPPED"})

            if not active_tasks:
                self.logger.info("    -> No active tasks for this file.")
                continue

            try:
                self._backup_file(file_path)
                original_content = file_path.read_text(encoding='utf-8', errors='ignore')

                new_content, chunk_results = self._process_file_in_chunks(
                    file_path.name,
                    abs_path_str,
                    original_content,
                    active_tasks
                )

                if not self._validate_integrity(original_content, new_content):
                    raise ValueError("Safety Guard: New content too short (<50%). Reverting.")

                if not self.dry_run:
                    file_path.write_text(new_content, encoding='utf-8')
                    self.logger.info(f"    -> [Success] File rewritten ({len(active_tasks)} tasks processed).")
                else:
                    self.logger.info(f"    -> [Dry Run] File would be rewritten ({len(active_tasks)} tasks processed).")

                results.extend(chunk_results)

            except Exception as e:
                self.logger.error(f"Failed to refactor {file_path.name}: {e}")
                for t in active_tasks:
                    results.append({**t, "final_status": "LLM_FAIL", "details": str(e)})

        report_path = self._save_report(results, report_filename)

        if EmailReporter and not self.dry_run and email_recipients:
            self._trigger_email_report(email_recipients, report_path, results, file_count)
        elif self.dry_run:
            self.logger.info("[!] Dry Run: Email report skipped.")
        elif not email_recipients:
            self.logger.info("[!] No email recipients configured. Report saved to: " + report_path)

        return {
            "status": "completed",
            "report_path": report_path,
            "results": results,
            "files_processed": file_count
        }

    def _process_file_in_chunks(self, filename: str, file_path_abs: str, content: str, all_tasks: List[Dict]) -> Tuple[str, List[Dict]]:
        """Process file in intelligent chunks, applying fixes to each."""
        chunks = self._smart_chunk_code(content)
        final_pieces = []
        processed_results = []
        prev_chunk_tail = ""

        # Stats
        total_issues_file = len(all_tasks)
        issues_resolved_so_far = 0
        total_chunks = len(chunks)

        for i, (chunk_text, start_line) in enumerate(chunks):
            chunk_line_count = chunk_text.count('\n')
            end_line = start_line + chunk_line_count

            chunk_tasks = []
            for task in all_tasks:
                try:
                    task_line = int(task.get('line_number', 0))
                    # Allow fuzzy matching (+/- 5 lines) for fixes as line numbers might drift slightly
                    if (start_line - 5) <= task_line <= (end_line + 5):
                        chunk_tasks.append(task)
                except ValueError:
                    continue

            if not chunk_tasks:
                final_pieces.append(chunk_text)
                prev_chunk_tail = self._get_tail_context(chunk_text)
                continue

            self.logger.info(f"    [Running] Chunk {i+1}/{total_chunks}: Fixing lines {start_line}-{end_line} ({len(chunk_tasks)} issues)...")

            start_chunk_time = time.time()
            try:
                if self.dry_run:
                    final_pieces.append(chunk_text)
                    for t in chunk_tasks:
                        processed_results.append({**t, "final_status": "FIXED_SIMULATED", "details": "Dry Run"})
                    self.logger.info(f"Done (Dry Run).")
                    continue

                # --- DEPENDENCY FETCH ---
                dependency_context = ""
                if self.dep_service:
                    dependency_context = self._fetch_dependencies(file_path_abs, start_line, end_line)

                prompt = self._construct_refactor_prompt(
                    filename, chunk_text, chunk_tasks, prev_chunk_tail, dependency_context
                )

                llm_response = self.llm_tools.llm_call(prompt)
                fixed_chunk = self._extract_code_from_response(llm_response)

                duration = round(time.time() - start_chunk_time, 1)

                if fixed_chunk:
                    if len(fixed_chunk) < len(chunk_text) * 0.4:
                        self.logger.warning(f"Failed (Truncated Response).")
                        final_pieces.append(chunk_text)
                        for t in chunk_tasks:
                            processed_results.append({**t, "final_status": "LLM_FAIL", "details": "Response truncated"})
                    else:
                        final_pieces.append(fixed_chunk)
                        issues_resolved_so_far += len(chunk_tasks)
                        self.logger.info(f"Done in {duration}s.")

                        for t in chunk_tasks:
                            processed_results.append({**t, "final_status": "FIXED", "details": f"Fixed in Chunk {i+1}"})
                        prev_chunk_tail = self._get_tail_context(fixed_chunk)
                else:
                    self.logger.warning(f"Failed (Empty Response).")
                    final_pieces.append(chunk_text)
                    prev_chunk_tail = self._get_tail_context(chunk_text)
                    for t in chunk_tasks:
                        processed_results.append({**t, "final_status": "LLM_FAIL", "details": "Invalid/Empty response"})

            except Exception as e:
                self.logger.error(f"Chunk processing error: {e}")
                final_pieces.append(chunk_text)
                prev_chunk_tail = self._get_tail_context(chunk_text)
                for t in chunk_tasks:
                    processed_results.append({**t, "final_status": "LLM_FAIL", "details": str(e)})

        return "".join(final_pieces), processed_results

    def _fetch_dependencies(self, file_path_abs: str, start_line: int, end_line: int) -> str:
        """
        Fetches semantic definitions (structs, globals) to guide the LLM fix.
        Uses ABSOLUTE path so DependencyService can resolve correctly.
        """
        try:
            response = self.dep_service.perform_fetch(
                project_root=str(self.codebase_root),
                output_dir=self.output_dir,
                codebase_identifier=self.project_name,
                endpoint_type="fetch_dependencies_by_file",
                file_name=file_path_abs,
                start=start_line,
                end=end_line,
                level=1
            )
            data = response.get("data", [])
            if not data:
                return ""

            context_str = []
            if isinstance(data, list):
                for item in data[:10]:
                    if isinstance(item, dict):
                        name = item.get("name", "Unknown")
                        kind = item.get("kind", "Unknown")
                        snippet = item.get("snippet", "").strip()
                        if snippet:
                            context_str.append(f"// ({kind}) {name}:\n{snippet}")

            return "\n\n".join(context_str)
        except Exception as e:
            self.logger.warning(f"Failed to fetch dependencies: {e}")
            return ""

    def _smart_chunk_code(self, content: str) -> List[Tuple[str, int]]:
        """Intelligently chunk code while respecting brace balance and line limits."""
        if len(content) < self.TARGET_CHUNK_CHARS * 1.5:
            return [(content, 1)]

        chunks = []
        current_pos = 0
        total_len = len(content)
        last_calc_pos = 0
        last_calc_line = 1

        def get_line_at_index(target_index):
            nonlocal last_calc_pos, last_calc_line
            if target_index > last_calc_pos:
                segment = content[last_calc_pos:target_index]
                newlines = segment.count('\n')
                last_calc_line += newlines
                last_calc_pos = target_index
            return last_calc_line

        while current_pos < total_len:
            start_index = current_pos
            start_line = get_line_at_index(start_index)

            if (total_len - start_index) < self.TARGET_CHUNK_CHARS:
                chunks.append((content[start_index:], start_line))
                break

            scan_idx = start_index
            brace_balance = 0
            found_split = False

            while scan_idx < total_len:
                char = content[scan_idx]
                if char == '{':
                    brace_balance += 1
                elif char == '}':
                    brace_balance -= 1

                chunk_size = scan_idx - start_index

                if chunk_size >= self.TARGET_CHUNK_CHARS and brace_balance <= 0:
                    split_idx = scan_idx + 1
                    chunks.append((content[start_index:split_idx], start_line))
                    current_pos = split_idx
                    found_split = True
                    break

                if chunk_size >= self.HARD_CHUNK_LIMIT:
                    newline_pos = content.find('\n', scan_idx)
                    split_idx = newline_pos + 1 if newline_pos != -1 else scan_idx + 1
                    chunks.append((content[start_index:split_idx], start_line))
                    current_pos = split_idx
                    found_split = True
                    break

                scan_idx += 1

            if not found_split:
                chunks.append((content[start_index:], start_line))
                break

        return chunks

    def _get_tail_context(self, text: str) -> str:
        """Extract tail context from text for inter-chunk continuity."""
        lines = text.splitlines()
        if len(lines) > self.CONTEXT_OVERLAP_LINES:
            return "\n".join(lines[-self.CONTEXT_OVERLAP_LINES:])
        return text

    def _construct_refactor_prompt(self, filename: str, content: str, issues: List[Dict], preceding_context: str, dependency_context: str) -> str:
        """Construct a detailed refactoring prompt for the LLM."""
        issues_text = ""
        for i, issue in enumerate(issues, 1):
            issues_text += (
                f"--- ISSUE #{i} ---\n"
                f"Location: Line {issue.get('line_number')}\n"
                f"Problem: {issue.get('rationale')}\n"
                f"Suggested Fix: {issue.get('suggested_fix')}\n"
                f"Constraint: {issue.get('constraints', 'None')}\n\n"
            )

        context_section = ""
        if preceding_context:
            context_section += (
                f"--- PREVIOUS CHUNK CONTEXT ---\n"
                f"// ... end of previous lines\n"
                f"{preceding_context}\n"
                f"// ... current chunk follows\n\n"
            )

        if dependency_context:
            context_section += (
                f"--- EXTERNAL DEFINITIONS (SEMANTIC CONTEXT) ---\n"
                f"// Use these definitions (structs, macros, globals) to ensure your fix is valid.\n"
                f"{dependency_context}\n\n"
            )

        return f"""
            You are a Secure C++ Refactoring Agent.
            Fix the reported issues in the "CODE FRAGMENT TO FIX" below.

            {context_section}

            --- ISSUES TO RESOLVE ---
            {issues_text}

            --- CODE FRAGMENT TO FIX ---
            ```cpp
            {content}
            ```

            CRITICAL OUTPUT INSTRUCTIONS:
            1. You MUST return the **ENTIRE** content of the "CODE FRAGMENT TO FIX" with the fixes applied.
            2. DO NOT use placeholder comments like "// ... existing code ...". Return the full code.
            3. Verify your fix against the "EXTERNAL DEFINITIONS" provided above (e.g., check struct member names).
            4. If you return truncated code, the system will REJECT your fix.
            """

    def _load_directives(self) -> List[Dict]:
        """Load refactoring directives from JSONL file."""
        tasks = []
        if not self.directives_path.exists():
            return []
        try:
            with open(self.directives_path, 'r') as f:
                for line in f:
                    if line.strip():
                        try:
                            tasks.append(json.loads(line))
                        except json.JSONDecodeError as e:
                            self.logger.debug(f"Skipping malformed JSON line: {e}")
                            continue
        except Exception as e:
            self.logger.error(f"Failed to load directives file: {e}")
        return tasks

    def _group_by_file(self, directives: List[Dict]) -> Dict[str, List[Dict]]:
        """Group directives by file path."""
        grouped = {}
        for t in directives:
            if t.get('file_path'):
                grouped.setdefault(t['file_path'], []).append(t)
        return grouped

    def _extract_code_from_response(self, response: str) -> Optional[str]:
        """Extract code from LLM response (handles markdown code blocks and plain code)."""
        match = re.search(r"```(?:\w+)?\n(.*?)```", response, re.DOTALL)
        if match:
            return match.group(1).strip()
        if any(kw in response for kw in ["#include", "namespace", "class", "void ", "int "]):
            return response.strip()
        return None

    def _validate_integrity(self, original: str, new: str) -> bool:
        """Validate that the new content is substantially similar to original."""
        return len(new) >= len(original) * 0.5

    def _backup_file(self, file_path: Path):
        """Backup file before modification."""
        if self.dry_run:
            return
        try:
            if file_path.is_relative_to(self.codebase_root):
                rel_path = file_path.relative_to(self.codebase_root)
            else:
                rel_path = file_path.name

            dest_path = self.backup_dir / rel_path
            dest_path.parent.mkdir(parents=True, exist_ok=True)
            if not dest_path.exists():
                shutil.copy2(file_path, dest_path)
        except Exception as e:
            if self.verbose:
                self.logger.warning(f"    [!] Backup failed: {e}")

    def _save_report(self, results: List[Dict], filename: str) -> str:
        """
        Saves the execution report as a beautifully formatted Excel file.
        Uses ExcelWriter for consistent formatting.
        """
        output_path = str(Path(filename).resolve())
        # Ensure output directory exists
        Path(output_path).parent.mkdir(parents=True, exist_ok=True)

        if not results:
            return ""

        try:
            # Prepare summary metadata
            total_tasks = len(results)
            fixed_count = sum(1 for r in results if r.get('final_status') == 'FIXED')
            failed_count = sum(1 for r in results if 'FAIL' in str(r.get('final_status', '')))
            skipped_count = sum(1 for r in results if r.get('final_status') == 'SKIPPED')

            summary_metadata = {
                "Total Tasks": str(total_tasks),
                "Successfully Fixed": str(fixed_count),
                "Failed/Pending": str(failed_count),
                "Skipped": str(skipped_count),
                "Execution Date": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                "Codebase": str(self.codebase_root.name),
                "Mode": "DRY RUN" if self.dry_run else "LIVE"
            }

            # Reorder columns for better readability
            preferred_order = ['file_path', 'line_number', 'severity', 'final_status', 'rationale', 'suggested_fix', 'details']
            available_columns = list(dict.fromkeys([c for c in preferred_order if c in (results[0].keys() if results else [])] +
                                                     [c for c in results[0].keys() if c not in preferred_order]))

            # Create writer and add sheets
            writer = ExcelWriter(output_path)
            writer.add_data_sheet(summary_metadata, "Summary", "Codebase Fixer Execution Report")
            writer.add_table_sheet(available_columns, results, "Audit Log", status_column="final_status")
            writer.save()

            self.logger.info(f"Report saved to: {output_path}")
            return output_path

        except Exception as e:
            self.logger.error(f"Excel report generation failed ({e}), falling back to JSON.")
            json_path = output_path.replace('.xlsx', '.json')
            try:
                with open(json_path, 'w') as f:
                    json.dump(results, f, indent=2, default=str)
                return json_path
            except Exception as e2:
                self.logger.error(f"JSON fallback also failed: {e2}")
                return ""

    def _trigger_email_report(self, recipients: List[str], attachment_path: str, results: List[Dict], file_count: int):
        """
        Sends a comprehensive email report with execution summary and Excel attachment.
        """
        try:
            total_tasks = len(results)
            fixed_count = sum(1 for r in results if r.get('final_status') == 'FIXED')
            failed_count = sum(1 for r in results if r.get('final_status') in ['LLM_FAIL', 'FILE_NOT_FOUND', 'SKIPPED'])

            modified_files_set = set()
            for r in results:
                if r.get('final_status') == 'FIXED':
                    modified_files_set.add(r.get('file_path', 'unknown'))

            modified_count = len(modified_files_set)

            mod_files_list = sorted([Path(p).name for p in modified_files_set])
            if len(mod_files_list) > 5:
                files_display = ", ".join(mod_files_list[:5]) + f", and {len(mod_files_list)-5} others."
            elif mod_files_list:
                files_display = ", ".join(mod_files_list)
            else:
                files_display = "None"

            end_time = datetime.now()
            duration_str = str(end_time - self.start_time).split('.')[0]

            metadata = {
                "Agent Type": "CodebaseFixerAgent (GenAI)",
                "Execution Mode": "DRY RUN (Simulation)" if self.dry_run else "LIVE (Changes Applied)",
                "Project Root": self.codebase_root.name,
                "Full Path": str(self.codebase_root),
                "Start Time": self.start_time.strftime("%Y-%m-%d %H:%M:%S"),
                "End Time": end_time.strftime("%Y-%m-%d %H:%M:%S"),
                "Duration": duration_str,
                "Backup Location": str(self.backup_dir) if not self.dry_run else "N/A"
            }

            stats = {
                "Files Modified": str(modified_count),
                "Total Tasks": str(total_tasks),
                "Fixed Successfully": str(fixed_count),
                "Pending/Failed": str(failed_count)
            }

            analysis_summary = (
                f"The agent successfully analyzed {file_count} files and applied {fixed_count} automated fixes "
                f"across {modified_count} files. Files updated: {files_display}. "
                f"{failed_count} items require manual review."
            )

            reporter = EmailReporter()
            success = reporter.send_report(
                recipients=recipients,
                metadata=metadata,
                stats=stats,
                analysis_summary=analysis_summary,
                attachment_path=attachment_path,
                subject="Codebase Fixer Agent - Execution Report",
                title="Codebase Refactoring Report"
            )

            if success:
                self.logger.info(f"Report email sent to {', '.join(recipients)}")
            else:
                self.logger.warning("Report email delivery failed.")

        except Exception as e:
            self.logger.error(f"Report trigger failed: {e}")

    def get_results(self) -> Dict:
        """
        Get current execution results. Can be called after run_agent for pipeline integration.

        Returns:
            Dictionary with execution metadata and results
        """
        return {
            "project": str(self.codebase_root),
            "start_time": self.start_time.isoformat(),
            "dry_run": self.dry_run,
            "output_dir": self.output_dir
        }
