import os
import json
import shutil
import logging
import re
import pandas as pd
from typing import List, Dict, Optional, Tuple
from pathlib import Path
from datetime import datetime
import time

# -------------------------------------------------------------------------
# DEPENDENCY SERVICE INTEGRATION
# -------------------------------------------------------------------------
try:
    # Assumes dependency_service.py is in the python path
    from dependency_builder.dependency_service import DependencyService
    DEPENDENCY_SERVICE_AVAILABLE = True
except ImportError:
    print("[!] Warning: DependencyService not found. Fixes will lack semantic context.")
    DependencyService = None
    DEPENDENCY_SERVICE_AVAILABLE = False

# -------------------------------------------------------------------------
# LLM TOOLS INTEGRATION
# -------------------------------------------------------------------------
try:
    from utils.common.llm_tools import LLMTools
except ImportError:
    print("[!] Warning: LLMTools not found. Running in Mock/Test Mode.")
    class LLMTools:
        def __init__(self, provider=None, model=None):
            self.provider = provider
            self.model = model
        def llm_call(self, prompt):
            return "Error: LLMTools not found. Cannot generate fix."

# -------------------------------------------------------------------------
# EMAIL REPORTER INTEGRATION
# -------------------------------------------------------------------------
try:
    from utils.common.email_reporter import CodebaseEmailReporter
except ImportError:
    CodebaseEmailReporter = None

class CodebaseFixerAgent:
    """
    Holistic Fixer Agent with Semantic Context Awareness.
    
    UPDATES:
    1. Uses DependencyService to inject struct/function definitions into the prompt.
    2. Maintains strict chunking and safety guards.
    3. Reads from the shared CCLS cache generated by the Analysis Agent.
    4. FIXED: Now passes ABSOLUTE paths to DependencyService to prevent 'File not found' errors.
    """
    
    TARGET_CHUNK_CHARS = 8000   
    HARD_CHUNK_LIMIT = 20000     
    CONTEXT_OVERLAP_LINES = 25

    def __init__(
        self, 
        codebase_root: str, 
        directives_file: str, 
        backup_dir: str,
        output_dir: str = "./out", # Path to where CCLS artifacts/cache are stored
        llm_config: Optional[Dict] = None,
        dry_run: bool = False,
        verbose: bool = False
    ):
        self.codebase_root = Path(codebase_root).resolve()
        self.directives_path = Path(directives_file).resolve()
        self.backup_dir = Path(backup_dir).resolve()
        self.output_dir = str(Path(output_dir).resolve()) # Ensure absolute path
        self.project_name = self.codebase_root.name
        self.start_time = datetime.now()
        
        # Configuration
        self.llm_config = llm_config or {}
        self.dry_run = dry_run
        self.verbose = verbose

        # Setup Logging
        logging.basicConfig(
            filename='fixer_agent_debug.log', 
            level=logging.INFO,
            format='%(asctime)s - %(levelname)s - %(message)s'
        )
        self.logger = logging.getLogger()

        # Initialize Services
        self.llm_tools = self._initialize_llm_tools()
        self.dep_service = DependencyService() if DEPENDENCY_SERVICE_AVAILABLE else None

    def _initialize_llm_tools(self):
        cli_key = self.llm_config.get("api_key")
        provider = self.llm_config.get("provider", "qgenie").lower()

        if cli_key:
            if self.verbose:
                print(f"[Agent] Configuration: Overriding {provider} API Key from CLI arguments.")
            if provider == "openai":
                os.environ["OPENAI_API_KEY"] = cli_key
            elif provider == "anthropic":
                os.environ["ANTHROPIC_API_KEY"] = cli_key
            elif provider in ["gemini", "google"]:
                os.environ["GOOGLE_API_KEY"] = cli_key
        else:
            if self.verbose:
                print(f"[Agent] Configuration: No CLI API Key provided. Using existing Environment Variables (if any).")

        try:
            tools = LLMTools() 
            if hasattr(tools, 'set_model') and self.llm_config.get('model'):
                tools.set_model(self.llm_config['model'])
            if self.verbose:
                print(f"[Agent] LLM Initialized (Provider: {provider})")
            return tools
        except Exception as e:
            print(f"[!] Error initializing LLMTools: {e}")
            return LLMTools() 

    def run_agent(self, report_filename: str = "final_execution_audit.xlsx", email_recipient: str = "sendpavanr@gmail.com"):
        print(f"[*] Starting Holistic Fixer Agent on {self.codebase_root}")
        if self.dep_service:
            print(f"[*] Dependency Service Enabled. Using cache at: {self.output_dir}/{self.project_name}")
        
        if self.dry_run:
            print("    [NOTICE] DRY RUN MODE ENABLED: No files will be modified.")
        
        directives = self._load_directives()
        if not directives:
            print("[!] No directives found.")
            return

        grouped_tasks = self._group_by_file(directives)
        results = []
        file_count = 0
        total_files = len(grouped_tasks)

        for file_path_str, tasks in grouped_tasks.items():
            file_count += 1
            # Path resolution
            if os.path.isabs(file_path_str):
                try:
                    file_path = Path(file_path_str).resolve()
                except ValueError:
                    file_path = Path(file_path_str)
            else:
                file_path = (self.codebase_root / file_path_str).resolve()
            
            # Use Absolute Path for dependency lookup to avoid ambiguity
            abs_path_str = str(file_path)

            print(f"[{file_count}/{total_files}] Processing File: {file_path.name} ({len(tasks)} items)...")

            if not file_path.exists():
                print(f"    [!] File not found: {file_path}")
                for t in tasks: results.append({**t, "final_status": "FILE_NOT_FOUND"})
                continue

            active_tasks = [t for t in tasks if t.get('action') != 'SKIP']
            skipped_tasks = [t for t in tasks if t.get('action') == 'SKIP']

            for t in skipped_tasks:
                results.append({**t, "final_status": "SKIPPED"})

            if not active_tasks:
                print("    -> No active tasks for this file.")
                continue

            try:
                self._backup_file(file_path)
                original_content = file_path.read_text(encoding='utf-8', errors='ignore')

                new_content, chunk_results = self._process_file_in_chunks(
                    file_path.name,
                    abs_path_str, # Passing absolute path here
                    original_content, 
                    active_tasks
                )

                if not self._validate_integrity(original_content, new_content):
                    raise ValueError("Safety Guard: New content too short (<50%). Reverting.")

                if not self.dry_run:
                    file_path.write_text(new_content, encoding='utf-8')
                    print(f"    -> [Success] File rewritten ({len(active_tasks)} tasks processed).")
                else:
                    print(f"    -> [Dry Run] File would be rewritten ({len(active_tasks)} tasks processed).")

                results.extend(chunk_results)

            except Exception as e:
                print(f"    [!] Failed to refactor {file_path.name}: {e}")
                self.logger.error(f"Failed to refactor {file_path}: {e}")
                for t in active_tasks:
                    results.append({**t, "final_status": "LLM_FAIL", "details": str(e)})

        report_path = self._save_report(results, report_filename)

        if CodebaseEmailReporter and not self.dry_run:
            self._trigger_email_report(email_recipient, report_path, results, file_count)
        elif self.dry_run:
            print("[!] Dry Run: Email report skipped (enable if needed).")
        else:
            print("[!] Skipping report (Reporter not found).")

    def _process_file_in_chunks(self, filename: str, file_path_abs: str, content: str, all_tasks: List[Dict]) -> Tuple[str, List[Dict]]:
        chunks = self._smart_chunk_code(content)
        final_pieces = []
        processed_results = []
        prev_chunk_tail = ""
        
        # Stats
        total_issues_file = len(all_tasks)
        issues_resolved_so_far = 0
        total_chunks = len(chunks)

        for i, (chunk_text, start_line) in enumerate(chunks):
            chunk_line_count = chunk_text.count('\n')
            end_line = start_line + chunk_line_count
            
            chunk_tasks = []
            for task in all_tasks:
                try:
                    task_line = int(task.get('line_number', 0))
                    # Allow fuzzy matching (+/- 5 lines) for fixes as line numbers might drift slightly
                    if (start_line - 5) <= task_line <= (end_line + 5):
                        chunk_tasks.append(task)
                except ValueError:
                    continue
            
            if not chunk_tasks:
                final_pieces.append(chunk_text)
                prev_chunk_tail = self._get_tail_context(chunk_text)
                continue
            
            print(f"    [Running] Chunk {i+1}/{total_chunks}: Fixing lines {start_line}-{end_line} ({len(chunk_tasks)} issues)... ", end="", flush=True)
            
            start_chunk_time = time.time()
            try:
                if self.dry_run:
                     final_pieces.append(chunk_text)
                     for t in chunk_tasks:
                         processed_results.append({**t, "final_status": "FIXED_SIMULATED", "details": "Dry Run"})
                     print(f"Done (Dry Run).")
                     continue

                # --- DEPENDENCY FETCH ---
                dependency_context = ""
                if self.dep_service:
                    # Pass absolute path to leverage Smart Path Resolution in dependency builder
                    dependency_context = self._fetch_dependencies(file_path_abs, start_line, end_line)

                prompt = self._construct_refactor_prompt(
                    filename, chunk_text, chunk_tasks, prev_chunk_tail, dependency_context
                )
                
                llm_response = self.llm_tools.llm_call(prompt)
                fixed_chunk = self._extract_code_from_response(llm_response)
                
                duration = round(time.time() - start_chunk_time, 1)

                if fixed_chunk:
                    if len(fixed_chunk) < len(chunk_text) * 0.4:
                         print(f"Failed (Truncated Response).")
                         final_pieces.append(chunk_text)
                         for t in chunk_tasks:
                             processed_results.append({**t, "final_status": "LLM_FAIL", "details": "Response truncated"})
                    else:
                        final_pieces.append(fixed_chunk)
                        issues_resolved_so_far += len(chunk_tasks)
                        print(f"Done in {duration}s.")
                        
                        for t in chunk_tasks:
                            processed_results.append({**t, "final_status": "FIXED", "details": f"Fixed in Chunk {i+1}"})
                        prev_chunk_tail = self._get_tail_context(fixed_chunk)
                else:
                    print(f"Failed (Empty Response).")
                    final_pieces.append(chunk_text)
                    prev_chunk_tail = self._get_tail_context(chunk_text)
                    for t in chunk_tasks:
                        processed_results.append({**t, "final_status": "LLM_FAIL", "details": "Invalid/Empty response"})
                        
            except Exception as e:
                print(f"Error: {e}")
                final_pieces.append(chunk_text)
                prev_chunk_tail = self._get_tail_context(chunk_text)
                for t in chunk_tasks:
                    processed_results.append({**t, "final_status": "LLM_FAIL", "details": str(e)})

        return "".join(final_pieces), processed_results

    def _fetch_dependencies(self, file_path_abs: str, start_line: int, end_line: int) -> str:
        """
        Fetches semantic definitions (structs, globals) to guide the LLM fix.
        Uses ABSOLUTE path so DependencyService can resolve correctly.
        """
        try:
            response = self.dep_service.perform_fetch(
                project_root=str(self.codebase_root),
                output_dir=self.output_dir,
                codebase_identifier=self.project_name,
                endpoint_type="fetch_dependencies_by_file", 
                file_name=file_path_abs, # Absolute Path
                start=start_line,
                end=end_line,
                level=1 
            )
            data = response.get("data", [])
            if not data: return ""

            context_str = []
            if isinstance(data, list):
                for item in data[:10]: 
                    if isinstance(item, dict):
                        name = item.get("name", "Unknown")
                        kind = item.get("kind", "Unknown")
                        snippet = item.get("snippet", "").strip()
                        if snippet:
                            context_str.append(f"// ({kind}) {name}:\n{snippet}")
            
            return "\n\n".join(context_str)
        except:
            return ""

    def _smart_chunk_code(self, content: str) -> List[Tuple[str, int]]:
        if len(content) < self.TARGET_CHUNK_CHARS * 1.5:
            return [(content, 1)]

        chunks = []
        current_pos = 0
        total_len = len(content)
        last_calc_pos = 0
        last_calc_line = 1
        
        def get_line_at_index(target_index):
            nonlocal last_calc_pos, last_calc_line
            if target_index > last_calc_pos:
                segment = content[last_calc_pos:target_index]
                newlines = segment.count('\n')
                last_calc_line += newlines
                last_calc_pos = target_index
            return last_calc_line

        while current_pos < total_len:
            start_index = current_pos
            start_line = get_line_at_index(start_index)
            
            if (total_len - start_index) < self.TARGET_CHUNK_CHARS:
                chunks.append((content[start_index:], start_line))
                break

            scan_idx = start_index
            brace_balance = 0
            found_split = False
            
            while scan_idx < total_len:
                char = content[scan_idx]
                if char == '{': brace_balance += 1
                elif char == '}': brace_balance -= 1
                
                chunk_size = scan_idx - start_index
                
                if chunk_size >= self.TARGET_CHUNK_CHARS and brace_balance <= 0:
                    split_idx = scan_idx + 1
                    chunks.append((content[start_index:split_idx], start_line))
                    current_pos = split_idx
                    found_split = True
                    break
                
                if chunk_size >= self.HARD_CHUNK_LIMIT:
                    newline_pos = content.find('\n', scan_idx)
                    split_idx = newline_pos + 1 if newline_pos != -1 else scan_idx + 1
                    chunks.append((content[start_index:split_idx], start_line))
                    current_pos = split_idx
                    found_split = True
                    break
                    
                scan_idx += 1
            
            if not found_split:
                chunks.append((content[start_index:], start_line))
                break
                
        return chunks

    def _get_tail_context(self, text: str) -> str:
        lines = text.splitlines()
        if len(lines) > self.CONTEXT_OVERLAP_LINES:
            return "\n".join(lines[-self.CONTEXT_OVERLAP_LINES:])
        return text

    def _construct_refactor_prompt(self, filename: str, content: str, issues: List[Dict], preceding_context: str, dependency_context: str) -> str:
        issues_text = ""
        for i, issue in enumerate(issues, 1):
            issues_text += (
                f"--- ISSUE #{i} ---\n"
                f"Location: Line {issue.get('line_number')}\n"
                f"Problem: {issue.get('rationale')}\n"
                f"Suggested Fix: {issue.get('suggested_fix')}\n"
                f"Constraint: {issue.get('constraints', 'None')}\n\n"
            )

        context_section = ""
        if preceding_context:
            context_section += (
                f"--- PREVIOUS CHUNK CONTEXT ---\n"
                f"// ... end of previous lines\n"
                f"{preceding_context}\n"
                f"// ... current chunk follows\n\n"
            )
        
        if dependency_context:
            context_section += (
                f"--- EXTERNAL DEFINITIONS (SEMANTIC CONTEXT) ---\n"
                f"// Use these definitions (structs, macros, globals) to ensure your fix is valid.\n"
                f"{dependency_context}\n\n"
            )

        return f"""
            You are a Secure C++ Refactoring Agent.
            Fix the reported issues in the "CODE FRAGMENT TO FIX" below.
            
            {context_section}

            --- ISSUES TO RESOLVE ---
            {issues_text}

            --- CODE FRAGMENT TO FIX ---
            ```cpp
            {content}
            ```
            
            CRITICAL OUTPUT INSTRUCTIONS:
            1. You MUST return the **ENTIRE** content of the "CODE FRAGMENT TO FIX" with the fixes applied.
            2. DO NOT use placeholder comments like "// ... existing code ...". Return the full code.
            3. Verify your fix against the "EXTERNAL DEFINITIONS" provided above (e.g., check struct member names).
            4. If you return truncated code, the system will REJECT your fix.
            """

    def _load_directives(self) -> List[Dict]:
        tasks = []
        if not self.directives_path.exists(): return []
        try:
            with open(self.directives_path, 'r') as f:
                for line in f:
                    if line.strip():
                        try: tasks.append(json.loads(line))
                        except: continue
        except: pass
        return tasks

    def _group_by_file(self, directives: List[Dict]) -> Dict[str, List[Dict]]:
        grouped = {}
        for t in directives:
            if t.get('file_path'): grouped.setdefault(t['file_path'], []).append(t)
        return grouped

    def _extract_code_from_response(self, response: str) -> Optional[str]:
        match = re.search(r"```(?:\w+)?\n(.*?)```", response, re.DOTALL)
        if match: return match.group(1).strip()
        if any(kw in response for kw in ["#include", "namespace", "class", "void ", "int "]): return response.strip()
        return None

    def _validate_integrity(self, original: str, new: str) -> bool:
        return len(new) >= len(original) * 0.5

    def _backup_file(self, file_path: Path):
        if self.dry_run:
            return
        try:
            if file_path.is_relative_to(self.codebase_root):
                rel_path = file_path.relative_to(self.codebase_root)
            else:
                rel_path = file_path.name
                
            dest_path = self.backup_dir / rel_path
            dest_path.parent.mkdir(parents=True, exist_ok=True)
            if not dest_path.exists(): shutil.copy2(file_path, dest_path)
        except Exception as e:
            if self.verbose: print(f"    [!] Backup failed: {e}")
            pass

    def _save_report(self, results: List[Dict], filename: str) -> str:
        """
        Saves the execution report as a beautifully formatted Excel file.
        """
        output_path = str(Path(filename).resolve())
        # Ensure output directory exists
        Path(output_path).parent.mkdir(parents=True, exist_ok=True)

        if not results: return ""
        
        df = pd.DataFrame(results)
        
        preferred_order = ['file_path', 'line_number', 'severity', 'final_status', 'rationale', 'suggested_fix', 'details']
        cols = [c for c in preferred_order if c in df.columns] + [c for c in df.columns if c not in preferred_order]
        df = df[cols]

        try:
            with pd.ExcelWriter(output_path, engine='xlsxwriter') as writer:
                df.to_excel(writer, sheet_name='Audit Log', index=False)
                
                workbook = writer.book
                worksheet = writer.sheets['Audit Log']
                
                header_fmt = workbook.add_format({
                    'bold': True, 'text_wrap': True, 'valign': 'top', 
                    'fg_color': '#4F81BD', 'font_color': '#FFFFFF', 'border': 1
                })
                
                base_fmt = workbook.add_format({'text_wrap': True, 'valign': 'top'})
                status_fixed = workbook.add_format({'bg_color': '#C6EFCE', 'font_color': '#006100'})
                status_fail = workbook.add_format({'bg_color': '#FFC7CE', 'font_color': '#9C0006'})
                status_skip = workbook.add_format({'bg_color': '#FFEB9C', 'font_color': '#9C5700'})

                for col_num, value in enumerate(df.columns.values):
                    worksheet.write(0, col_num, value, header_fmt)

                worksheet.set_column('A:A', 30, base_fmt)   
                worksheet.set_column('B:B', 10, base_fmt)   
                worksheet.set_column('C:C', 12, base_fmt)   
                worksheet.set_column('D:D', 18, base_fmt)   
                worksheet.set_column('E:F', 50, base_fmt)   
                worksheet.set_column('G:Z', 40, base_fmt)   

                if 'final_status' in df.columns:
                    status_col_idx = df.columns.get_loc('final_status')
                    last_row = len(df)
                    worksheet.conditional_format(1, status_col_idx, last_row, status_col_idx, {
                        'type': 'text', 'criteria': 'containing', 'value': 'FIXED', 'format': status_fixed
                    })
                    worksheet.conditional_format(1, status_col_idx, last_row, status_col_idx, {
                        'type': 'text', 'criteria': 'containing', 'value': 'FAIL', 'format': status_fail
                    })
                    worksheet.conditional_format(1, status_col_idx, last_row, status_col_idx, {
                        'type': 'text', 'criteria': 'containing', 'value': 'SKIPPED', 'format': status_skip
                    })
            return output_path

        except Exception as e:
            print(f"    [!] Excel formatting failed ({e}), falling back to standard CSV.")
            csv_path = output_path.replace('.xlsx', '.csv')
            df.to_csv(csv_path, index=False)
            return csv_path

    def _trigger_email_report(self, recipient: str, attachment_path: str, results: List[Dict], file_count: int):
        """
        Sends a comprehensive HTML email report.
        """
        try:
            total_tasks = len(results)
            fixed_count = sum(1 for r in results if r.get('final_status') == 'FIXED')
            failed_count = sum(1 for r in results if r.get('final_status') in ['LLM_FAIL', 'FILE_NOT_FOUND', 'SKIPPED'])
            
            modified_files_set = set()
            for r in results:
                if r.get('final_status') == 'FIXED':
                    modified_files_set.add(r.get('file_path', 'unknown'))
            
            modified_count = len(modified_files_set)
            
            mod_files_list = sorted([Path(p).name for p in modified_files_set])
            if len(mod_files_list) > 5:
                files_display = ", ".join(mod_files_list[:5]) + f", and {len(mod_files_list)-5} others."
            elif mod_files_list:
                files_display = ", ".join(mod_files_list)
            else:
                files_display = "None"

            end_time = datetime.now()
            duration_str = str(end_time - self.start_time).split('.')[0]
            
            metadata = {
                "Agent Type": "CodebaseFixerAgent (GenAI)",
                "Execution Mode": "DRY RUN (Simulation)" if self.dry_run else "LIVE (Changes Applied)",
                "Project Root": self.codebase_root.name,
                "Full Path": str(self.codebase_root),
                "Start Time": self.start_time.strftime("%Y-%m-%d %H:%M:%S"),
                "End Time": end_time.strftime("%Y-%m-%d %H:%M:%S"),
                "Duration": duration_str,
                "Backup Location": str(self.backup_dir) if not self.dry_run else "N/A"
            }
            
            stats = {
                "Files Modified": modified_count,
                "Total Tasks": total_tasks,
                "Fixed Successfully": fixed_count,
                "Pending/Failed": failed_count
            }
            
            summary = (
                f"<b>Execution Summary:</b><br>"
                f"The agent successfully analyzed {file_count} files and applied <b>{fixed_count} automated fixes</b> across <b>{modified_count} files</b>.<br><br>"
                
                f"<b>Key Modifications:</b><br>"
                f"Files updated: {files_display}<br><br>"
                
                f"<b>Post-Processing Action Items:</b><br>"
                f"1. <b>Review Changes:</b> Open the attached <i>{Path(attachment_path).name}</i> to audit the specific lines changed and the LLM's rationale.<br>"
                f"2. <b>Regression Testing:</b> Execute project-level build and unit tests to ensure codebase integrity.<br>"
                f"3. <b>Backup Verification:</b> If critical errors occur, restore files from: <code>{self.backup_dir}</code><br>"
                f"4. <b>Manual Resolution:</b> {failed_count} items (marked RED in the Excel) require manual engineer review."
            )
            
            reporter = CodebaseEmailReporter()
            reporter.send_report(recipient, attachment_path, metadata, stats, summary)
            
        except Exception as e:
            print(f"[!] Report trigger failed: {e}")